"""Interactive setup wizard for koa-cli."""

from __future__ import annotations

import subprocess
from pathlib import Path

import yaml

from .ui import (
    confirm,
    console,
    print_bonsai,
    print_error,
    print_header,
    print_info,
    print_step,
    print_success,
    print_warning,
    prompt,
)


def test_ssh_connection(user: str, host: str) -> bool:
    """Test SSH connection to the remote host."""
    try:
        result = subprocess.run(
            ["ssh", "-o", "ConnectTimeout=10", "-o", "BatchMode=yes", f"{user}@{host}", "exit"],
            capture_output=True,
            timeout=15,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def run_setup() -> int:
    """Run the interactive setup wizard."""
    console.clear()

    print_header(
        "🌺 Koa CLI Setup Wizard 🌺",
        "Let's get you connected to the Koa HPC cluster!"
    )
    console.print()

    # Step 1: Get username
    print_step(1, 4, "Configure your UH NetID")
    print_info("This is your University of Hawaii username")
    username = prompt("Enter your UH NetID")

    if not username:
        print_error("Username is required!")
        return 1

    console.print()

    # Step 2: Get hostname
    print_step(2, 4, "Configure Koa hostname")
    hostname = prompt("Enter Koa hostname", default="koa.its.hawaii.edu")
    console.print()

    # Step 3: Storage configuration
    print_step(3, 5, "Configure storage directories")
    console.print()
    print_info("Koa has two storage tiers:")
    print_info("  • Home directory: 50 GB limit (good for code)")
    print_info("  • Lustre scratch: Large storage (good for data/outputs)")
    console.print()

    use_defaults = confirm("Use default storage settings?", default=True)

    if use_defaults:
        remote_workdir = "~/koa-jobs"
        remote_data_dir = f"/mnt/lustre/koa/scratch/{username}/koa-jobs"
        identity_file = None
        proxy_command = None
    else:
        console.print()
        print_info("Code directory (recommended: home directory)")
        remote_workdir = prompt("Remote code directory", default="~/koa-jobs")

        console.print()
        print_info("Data directory (recommended: Lustre scratch for large outputs)")
        remote_data_dir = prompt(
            "Remote data directory",
            default=f"/mnt/lustre/koa/scratch/{username}/koa-jobs"
        )

        if confirm("Do you need to specify an SSH identity file?", default=False):
            identity_file = prompt("SSH identity file path", default="~/.ssh/id_rsa")
        else:
            identity_file = None

        if confirm("Do you need to use an SSH proxy/jump host?", default=False):
            proxy_command = prompt("SSH proxy command")
        else:
            proxy_command = None

    console.print()

    # Step 4: Test connection
    print_step(4, 5, "Test SSH connection")
    print_info(f"Testing connection to {username}@{hostname}...")

    if test_ssh_connection(username, hostname):
        print_success("SSH connection successful!")
    else:
        print_warning("Could not verify SSH connection")
        print_info("This might be because:")
        print_info("  • You haven't set up SSH keys yet")
        print_info("  • Two-factor authentication is required")
        print_info("  • The hostname is incorrect")
        console.print()

        if not confirm("Continue with setup anyway?", default=True):
            print_error("Setup cancelled")
            return 1

    console.print()

    # Create config directory
    config_dir = Path.home() / ".config" / "koa-cli"
    config_file = config_dir / "config.yaml"

    if config_file.exists():
        print_warning(f"Config file already exists at {config_file}")
        if not confirm("Overwrite existing config?", default=False):
            print_error("Setup cancelled")
            return 1

    # Create config
    config_dir.mkdir(parents=True, exist_ok=True)

    config_data = {
        "user": username,
        "host": hostname,
        "remote_workdir": remote_workdir,
        "remote_data_dir": remote_data_dir,
    }

    if identity_file:
        config_data["identity_file"] = identity_file

    if proxy_command:
        config_data["proxy_command"] = proxy_command

    with open(config_file, "w") as f:
        f.write("# Koa CLI Configuration\n")
        f.write(f"# Generated by koa setup\n\n")
        yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)

    console.print()
    print_success(f"Configuration saved to {config_file}")
    console.print()

    # Show next steps
    console.print("[bold cyan]🎉 Setup complete! Next steps:[/bold cyan]")
    console.print()
    console.print("  1. Test your connection:")
    console.print("     [bold green]koa check[/bold green]")
    console.print()
    console.print("  2. Sync your code:")
    console.print("     [bold green]koa sync[/bold green]")
    console.print()
    console.print("  3. Submit a job:")
    console.print("     [bold green]koa submit your_script.slurm[/bold green]")
    console.print()
    console.print("  4. Check job status:")
    console.print("     [bold green]koa jobs[/bold green]")
    console.print()
    console.print("[dim]Happy computing on Koa! 🌺[/dim]", justify="center")
    console.print()

    return 0
